version: "3.8"
# https://docs.docker.com/compose/compose-file/

services:

  mysql:
    image: mysql:8
    # Set max_allowed_packet to 512M for provisioning
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8_bin' --init-connect='SET NAMES utf8;' --character-set-server=utf8 --collation-server=utf8_bin --lower-case-table-names=2 --max-connections=500
    container_name: kris_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - kris_mysql_data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d

  social-media-backend:
    image: social-media-backend:latest
    container_name: social-media-backend
    environment:
      "LOGGING_LEVEL_ROOT": "INFO"
      "LOGGING_LEVEL_COM_KRISTIAN_SOCMED": "DEBUG"
      "spring.datasource.url": "jdbc:mysql://mysql:3306/kris_test"
      "spring.datasource.username": "root"
      "spring.datasource.password": "root"
      "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect"
      "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver"
      "app.url": "http://localhost:8080"
      "app.front-url": "http://localhost"
      "mail.host": "smtp.gmail.com"
      "mail.port": "587"
      "mail.username": "smilenetix@gmail.com"
      "mail.password": "mnttoyyhmllghriq"
    ports:
      - '8080:8080'

volumes:
  kris_mysql_data:

networks:
  default:
    name: kris-default
